Feature/mongo
wefoxplatform/rustainers pull request #9
Opened 2023-11-24 15:30 UTC by MalikEljaouadiWefox

2023-11-24 15:54 UTC, IgorLaborieWefox requested changes
Great stuff.

Still have few minor issues to fix.
Try to amend the 'feat: add mongo' commit, I want to rebase the PR instead of creating a merge commit.

2023-11-24 15:54 UTC, IgorLaborieWefox commented on .rtx.toml
> +[tools]
🔨 **todo**: do not commit this file

2023-11-24 15:54 UTC, IgorLaborieWefox commented on rustainers/src/images/mongo.rs
> +///        .with_tag("7.2");
🔨 **todo**: This version does not exist, use replace by `6`

2023-11-25 11:30 UTC, davidB commented on .rtx.toml
> +[tools]
why?

2023-11-30 07:03 UTC, IgorLaborieWefox approved these changes

2023-11-30 07:04 UTC, merged